/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface PackageConfiguration {
    extends: [string, ...string[]] | string
    ignorePatterns?: string[]
    rules?: {
        publishConfig?: boolean
        license?: boolean
        engines?: boolean
        files?: boolean
        dependencies?: boolean
        devDependencies?: boolean
        scripts?: boolean
        packageType?: boolean
        exports?: boolean
        types?: boolean
        main?: boolean
    }
    template?: {
        [k: string]: string | undefined
    }
}
