/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */

export interface PackageConfiguration {
    extends: [string, ...string[]] | string
    ignorePatterns?: string[]
    rules?: {
        publishConfig?: boolean
        license?: boolean
        engines?: boolean
        files?: boolean
        dependencies?: boolean
        devDependencies?: boolean
        scripts?: boolean
    }
}

export interface LegacyPackageConfiguration {
    type: string
    template?: {
        exclude?: string[]
        lint?: {
            publishConfig?: boolean
            license?: boolean
            engines?: boolean
            files?: boolean
            dependencies?: boolean
            devDependencies?: boolean
            scripts?: boolean
            definition?: boolean
        }
        documentation?: string
    }
}

export type AnyPackageConfiguration =
    | {
          extends: [string, ...string[]] | string
          ignorePatterns?: string[]
          rules?: {
              publishConfig?: boolean
              license?: boolean
              engines?: boolean
              files?: boolean
              dependencies?: boolean
              devDependencies?: boolean
              scripts?: boolean
          }
      }
    | {
          type: string
          template?: {
              exclude?: string[]
              lint?: {
                  publishConfig?: boolean
                  license?: boolean
                  engines?: boolean
                  files?: boolean
                  dependencies?: boolean
                  devDependencies?: boolean
                  scripts?: boolean
                  definition?: boolean
              }
              documentation?: string
          }
      }
