name: Reusable release pipeline for NodeJS projects

on:
  workflow_call:
    inputs:
      beta_release:
        description: Create beta release
        type: boolean
        required: false
        default: false
      build_artifact_name:
        description: Name of the build artifact
        type: string
        required: true
      build_artifact_path:
        required: false
        type: string
      semantic_release:
        required: false
        type: boolean
        default: true
      publish_docs:
        description: Publish documentation folder to github pages
        type: string
        required: false
        default: 'true'
    secrets:
      GITHUB_NPM_TOKEN:
        description: Token to install GitHub packages with
        required: false
      NPM_TOKEN:
        description: Token to install npm packages with
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    if: inputs.semantic_release == 'true'
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to be able to publish to github packages
    steps:
      - uses: actions/checkout@v3
      - name: Download node standards
        uses: skyleague/node-standards/.github/actions/download-artifact@main
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ inputs.build_artifact_path }}
      - uses: skyleague/node-standards/.github/actions/setup-node@main
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: skyleague/node-standards/.github/actions/release@main
        with:
          dry_run: ${{ (github.ref == 'refs/heads/next' || github.ref == 'refs/heads/main' || inputs.beta_release) && 'false' || 'true' }}
          beta_release: ${{ inputs.beta_release && 'true' || 'false' }}
        env:
          # Uses GITHUB_TOKEN for publish permissions
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  documentation:
    concurrency: gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    if: ${{ inputs.publish_docs == 'true' && (github.ref == 'refs/heads/next' || github.ref == 'refs/heads/main') }}
    steps:
      - uses: actions/checkout@v3
      - uses: skyleague/node-standards/.github/actions/setup-node@main
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run build:docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
