name: tfsec

on:
  workflow_call:
    secrets:
      GITHUB_APP_ID:
        required: false
      GITHUB_APP_PEM:
        required: false
    inputs:
      terraform-version:
        description: 'Terraform version to use, default to (1.4.6)'
        required: true
        type: string
        default: '1.4.6'
      working-directory:
        description: 'From which directory do we need to set this up'
        required: true
        type: string
        default: './'
      preinstall:
        description: 'Preinstall command'
        required: false
        type: string
        default: ''
      postinstall:
        description: 'Postinstall command'
        required: false
        type: string
        default: ''
      cache-hash:
        description: 'Additional hash for caching'
        required: false
        type: string
        default: ''
      tfsec-var-files:
        description: 'Var files to include in testing'
        type: string
        required: false
        default: ''

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup terraform and cache
        uses: skyleague/node-standards/.github/actions/setup-terraform@main
        with:
          terraform-version: ${{ inputs.terraform-version }}
          working-directory: ${{ inputs.working-directory }}
          preinstall: ${{ inputs.preinstall }}
          postinstall: ${{ inputs.postinstall }}
          cache-hash: ${{ inputs.cache-hash }}
          github-app-id: ${{ secrets.GITHUB_APP_ID }}
          github-app-pem: ${{ secrets.GITHUB_APP_PEM }}
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.2

  tfsec-matrix:
    name: tfsec - ${{ matrix.var-file }}
    runs-on: ubuntu-latest
    if: inputs.tfsec-var-files != ''

    strategy:
      matrix:
        var-file: ${{ fromJson(inputs.tfsec-var-files) }}

    steps:
      - uses: actions/checkout@v4
      - name: setup terraform and cache
        uses: skyleague/node-standards/.github/actions/setup-terraform@main
        with:
          terraform-version: ${{ inputs.terraform-version }}
          working-directory: ${{ inputs.working-directory }}
          preinstall: ${{ inputs.preinstall }}
          postinstall: ${{ inputs.postinstall }}
          cache-hash: ${{ inputs.cache-hash }}
          github-app-id: ${{ secrets.GITHUB_APP_ID }}
          github-app-pem: ${{ secrets.GITHUB_APP_PEM }}
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.2
        with:
          additional_args: --var-file=${{ matrix.var-file }}

  validate:
    name: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup terraform and cache
        uses: skyleague/node-standards/.github/actions/setup-terraform@main
        with:
          terraform-version: ${{ inputs.terraform-version }}
          working-directory: ${{ inputs.working-directory }}
          preinstall: ${{ inputs.preinstall }}
          postinstall: ${{ inputs.postinstall }}
          cache-hash: ${{ inputs.cache-hash }}
          github-app-id: ${{ secrets.GITHUB_APP_ID }}
          github-app-pem: ${{ secrets.GITHUB_APP_PEM }}
      - run: terraform validate

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup terraform and cache
        uses: skyleague/node-standards/.github/actions/setup-terraform@main
        with:
          terraform-version: ${{ inputs.terraform-version }}
          working-directory: ${{ inputs.working-directory }}
          preinstall: ${{ inputs.preinstall }}
          postinstall: ${{ inputs.postinstall }}
          cache-hash: ${{ inputs.cache-hash }}
          github-app-id: ${{ secrets.GITHUB_APP_ID }}
          github-app-pem: ${{ secrets.GITHUB_APP_PEM }}
      - run: terraform fmt -check
